Add some missing recipes
GregTech-Intergalactical/GregTech pull request #142
Opened 2022-11-19 05:16 UTC by lynxx131

Added in some missing crafting recipes:

- Bronze dust
- Vacum freezer
- Electric Forge hammer
- Implosion Compressor
- Multi smelter
- Heat Exchanger
- Distillation Tower
- Cracking Unit
- Battery buffer nine
- Fluid input and output hatches
- Item output hatch
- Energy hatch

This is an attempt address #135, but there's probably more recipes that I missed.

2022-11-19 15:35 UTC, Trinsdar requested changes

2022-11-19 15:35 UTC, Trinsdar commented on common/src/main/java/muramasa/gregtech/loader/crafting/MaterialCrafting.java
> +        provider.addItemRecipe(output, Ref.ID, recipeName, "misc", "has_wrench",
This should be a shapeless recipe.

2022-11-20 00:41 UTC, lynxx131 commented on common/src/main/java/muramasa/gregtech/loader/crafting/MaterialCrafting.java
> +        provider.addItemRecipe(output, Ref.ID, recipeName, "misc", "has_wrench",
Fixed

2022-11-20 03:19 UTC, Trinsdar approved these changes

2022-11-23 02:25 UTC, lynxx131 commented
Is there anything this PR is waiting on before being merged?

2022-11-24 06:12 UTC, merged