nuclear fission madness
GregTech-Intergalactical/GregTech pull request #160
Opened 2023-03-07 09:22 UTC by Rundas01

will be a draft at first. that will be changed once it's finished.

2023-03-07 15:08 UTC, Trinsdar commented
Fyi gui textures are going to have to be changed based on the old textures i put in instead, don't worry about the modern textures it's been using, i'll fix those in the included resource pack

2023-03-08 00:26 UTC, Trinsdar requested changes

2023-03-08 00:26 UTC, Trinsdar commented on common/src/main/java/muramasa/gregtech/loader/machines/ChemicalReactorLoader.java
> +        CHEMICAL_REACTING.RB().ii(of(DUST.get(Uranium,1))).fi(LeachingSolution.getLiquid(1000)).fo(LeachedUranium.getLiquid(1000)).add("uranium_leaching",120,1000);
these are the same exact recipes

2023-03-08 00:26 UTC, Trinsdar commented on common/src/main/java/muramasa/gregtech/loader/machines/ChemicalReactorLoader.java
> +        CHEMICAL_REACTING.RB().fi(Thoriumdioxidedinitrate.getLiquid(10000),Ammonia.getGas(22000)).fo(Ammoniumdithoranate.getLiquid(5000)).add("uranium_leaching",120,1000);
ammonium dithoranate does not seem to have a gas or liquid

2023-03-08 08:43 UTC, Rundas01 commented on common/src/main/java/muramasa/gregtech/loader/machines/ChemicalReactorLoader.java
> +        CHEMICAL_REACTING.RB().ii(of(DUST.get(Uranium,1))).fi(LeachingSolution.getLiquid(1000)).fo(LeachedUranium.getLiquid(1000)).add("uranium_leaching",120,1000);
true, must have happened while copy/pasting stuff. will remove the dupes ofc

2023-03-08 08:47 UTC, Rundas01 commented on common/src/main/java/muramasa/gregtech/loader/machines/ChemicalReactorLoader.java
> +        CHEMICAL_REACTING.RB().fi(Thoriumdioxidedinitrate.getLiquid(10000),Ammonia.getGas(22000)).fo(Ammoniumdithoranate.getLiquid(5000)).add("uranium_leaching",120,1000);
probably because they should be dusts

2023-03-10 09:17 UTC, Rundas01 commented
probably became unnecessary, due to the new PR I've opened. will close this once confirmed.

2023-03-12 09:24 UTC, Rundas01 commented
decame unecessary

2023-03-12 09:24 UTC, closed without merging